[package]
name = "sqlite"
version = "0.1.0"
authors = ["tahuy <anhhuy0701@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.24.2"